package projetIDE.model.ast;
/* Generated By:JJTree: Do not edit this line. ASTClassBody.java */

public class ASTClassBody extends SimpleNode {
  public ASTClassBody(int id) {
    super(id);
  }

  public ASTClassBody(JavaParser p, int id) {
    super(p, id);
  }

}
