package projetIDE.model.ast;
/* Generated By:JJTree: Do not edit this line. ASTClassBodyDeclaration.java */

public class ASTClassBodyDeclaration extends SimpleNode {
  public ASTClassBodyDeclaration(int id) {
    super(id);
  }

  public ASTClassBodyDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
