package projetIDE.model.ast;
/* Generated By:JJTree: Do not edit this line. ASTInterfaceMemberDeclaration.java */

public class ASTInterfaceMemberDeclaration extends SimpleNode {
  public ASTInterfaceMemberDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceMemberDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
