package projetIDE.model.ast;
/* Generated By:JJTree: Do not edit this line. ASTNestedClassDeclaration.java */

public class ASTNestedClassDeclaration extends SimpleNode {
  public ASTNestedClassDeclaration(int id) {
    super(id);
  }

  public ASTNestedClassDeclaration(JavaParser p, int id) {
    super(p, id);
  }
 
}
