package projetIDE.model.ast;
/* Generated By:JJTree: Do not edit this line. ASTUnmodifiedInterfaceDeclaration.java */

public class ASTUnmodifiedInterfaceDeclaration extends SimpleNode {
  public ASTUnmodifiedInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTUnmodifiedInterfaceDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
